"""Durable, user-visible workflow states.

Keep these states specific enough that a restart or a blocked provider task is
not reported as a generic failure.
"""

from __future__ import annotations

from enum import StrEnum


class JobStatus(StrEnum):
    PENDING = "PENDING"
    RUNNING = "RUNNING"
    PAUSED_CHALLENGE = "PAUSED_CHALLENGE"
    WAITING_PROVIDER = "WAITING_PROVIDER"
    PROVIDER_CAPACITY_WAIT = "PROVIDER_CAPACITY_WAIT"
    SUBMISSION_UNKNOWN = "SUBMISSION_UNKNOWN"
    MANUAL_RECONCILIATION = "MANUAL_RECONCILIATION"
    WAITING_REFILL = "WAITING_REFILL"
    WAITING_AGENT = "WAITING_AGENT"
    WAITING_EXTERNAL_UPLOAD = "WAITING_EXTERNAL_UPLOAD"
    WAITING_EXTERNAL_EXPORT = "WAITING_EXTERNAL_EXPORT"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    SUCCEEDED = "SUCCEEDED"
    SUPPLY_EXHAUSTED = "SUPPLY_EXHAUSTED"
    JOB_BLOCKED_SOFTWARE_ERROR = "JOB_BLOCKED_SOFTWARE_ERROR"
    FAILED = "FAILED"
    CANCELLED = "CANCELLED"


class ItemState(StrEnum):
    """Canonical per-candidate state machine used by both interfaces."""

    DISCOVERED = "DISCOVERED"
    HISTORICAL_DUPLICATE = "HISTORICAL_DUPLICATE"
    CAPTURE_READY = "CAPTURE_READY"
    CAPTURE_REJECTED = "CAPTURE_REJECTED"
    MEDIA_READY = "MEDIA_READY"
    MEDIA_REJECTED = "MEDIA_REJECTED"
    VISUAL_PENDING = "VISUAL_PENDING"
    VISUAL_ACCEPTED = "VISUAL_ACCEPTED"
    VISUAL_REJECTED = "VISUAL_REJECTED"
    CATEGORY_ACCEPTED = "CATEGORY_ACCEPTED"
    CATEGORY_REJECTED = "CATEGORY_REJECTED"
    DATE_ACCEPTED = "DATE_ACCEPTED"
    DATE_REJECTED = "DATE_REJECTED"
    DIMENSION_PENDING = "DIMENSION_PENDING"
    DIMENSION_READY = "DIMENSION_READY"
    DIMENSION_REJECTED = "DIMENSION_REJECTED"
    NAMING_READY = "NAMING_READY"
    NAMING_REVIEW = "NAMING_REVIEW"
    CATALOG_READY = "CATALOG_READY"
    MODEL_INPUT_LOCKED = "MODEL_INPUT_LOCKED"
    SUBMITTING = "SUBMITTING"
    PROVIDER_ACTIVE = "PROVIDER_ACTIVE"
    PROVIDER_SUCCESS = "PROVIDER_SUCCESS"
    PROVIDER_FAILED = "PROVIDER_FAILED"
    RAW_GLB_READY = "RAW_GLB_READY"
    RAW_GLB_INVALID = "RAW_GLB_INVALID"
    COMPLETED = "COMPLETED"
    ORDER_COMPLETE_NOT_NEEDED = "ORDER_COMPLETE_NOT_NEEDED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    QUARANTINED_SUBMISSION_UNKNOWN = "QUARANTINED_SUBMISSION_UNKNOWN"
    ABANDONED_SUBMISSION_UNKNOWN = "ABANDONED_SUBMISSION_UNKNOWN"
    HARD_STOP_ITEM = "HARD_STOP_ITEM"


class FailureDisposition(StrEnum):
    """Action for a failure; item failures do not implicitly fail the order."""

    NONE = "NONE"
    RETRY_ITEM = "RETRY_ITEM"
    REPLACE_CANDIDATE = "REPLACE_CANDIDATE"
    WAIT_PROVIDER = "WAIT_PROVIDER"
    SUPPLY_EXHAUSTED = "SUPPLY_EXHAUSTED"
    MANUAL_REVIEW = "MANUAL_REVIEW"
    SOFTWARE_AUTO_REPAIR = "SOFTWARE_AUTO_REPAIR"
    HARD_STOP = "HARD_STOP"


ACTIVE_STATUSES = {
    JobStatus.PENDING,
    JobStatus.RUNNING,
    JobStatus.WAITING_PROVIDER,
    JobStatus.PROVIDER_CAPACITY_WAIT,
    JobStatus.WAITING_REFILL,
    JobStatus.WAITING_AGENT,
    JobStatus.WAITING_EXTERNAL_UPLOAD,
    JobStatus.WAITING_EXTERNAL_EXPORT,
}

NON_RETRYABLE_STATUSES = {
    JobStatus.SUBMISSION_UNKNOWN,
    JobStatus.MANUAL_RECONCILIATION,
    JobStatus.SUPPLY_EXHAUSTED,
    JobStatus.JOB_BLOCKED_SOFTWARE_ERROR,
    JobStatus.CANCELLED,
}


def status_value(value: JobStatus | str) -> str:
    return value.value if isinstance(value, JobStatus) else str(value)
